quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/

conquery.frontend.query-upload.ids[0].name=ID
conquery.frontend.query-upload.ids[0].field=pid
conquery.frontend.query-upload.ids[0].label=result
conquery.frontend.query-upload.ids[0].primary-id=true
conquery.frontend.query-upload.ids[0].print=true

conquery.datasets[0].id=imdb
conquery.datasets[0].label=IMDb
conquery.datasets[1].id=empty-set
conquery.datasets[1].label=Empty Dataset