quarkus.log.category."com.bakdata.conquery".level=DEBUG

# Conquery related
conquery.metadata.enabled=true
conquery.metadata.root-path=target/test-classes/test-meta-data
conquery.metadata.folders[0]=imdb
conquery.metadata.folders[1]=empty_set

conquery.entity-preview.all[0].name=all:entities
conquery.entity-preview.all[0].label=Entities
conquery.entity-preview.default[0].name=default:entities
conquery.entity-preview.default[0].label=Entities
