quarkus.http.port=8090
quarkus.http.root-path=/
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

# Build-time selection of manager meta storage backend: IN_MEMORY or XODUS.
conquery.storage.backend=IN_MEMORY

conquery.datasets[0].id=imdb
conquery.datasets[0].label=IMDb
conquery.datasets[1].id=empty-set
conquery.datasets[1].label=Empty Dataset

conquery.concepts[0].id=imdb
conquery.concepts[0].label=IMDb
conquery.concepts[0].dataset=imdb

conquery.tables[0].id=imdb.title
conquery.tables[0].label=Titles
conquery.tables[0].dataset=imdb
conquery.tables[0].primary-column=imdb.title.id
conquery.tables[0].columns[0].id=imdb.title.id
conquery.tables[0].columns[0].label=Title ID
conquery.tables[0].columns[0].type=INTEGER
conquery.tables[0].columns[0].secondary-id=pid
conquery.tables[0].columns[1].id=imdb.title.name
conquery.tables[0].columns[1].label=Title
conquery.tables[0].columns[1].type=STRING
conquery.tables[0].columns[2].id=imdb.title.release_date
conquery.tables[0].columns[2].label=Release Date
conquery.tables[0].columns[2].type=DATE

conquery.entity-preview.all[0].name=imdb:entities
conquery.entity-preview.all[0].label=Entities
conquery.entity-preview.default[0].name=imdb:entities
conquery.entity-preview.default[0].label=Entities

conquery.frontend.query-upload.ids[0].name=ID
conquery.frontend.query-upload.ids[0].field=pid
conquery.frontend.query-upload.ids[0].label.und=result
conquery.frontend.query-upload.ids[0].primary-id=true
conquery.frontend.query-upload.ids[0].print=true
