quarkus.http.port=8090
quarkus.http.root-path=/
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

conquery.datasets[0].id=imdb
conquery.datasets[0].label=IMDb
conquery.datasets[1].id=empty-set
conquery.datasets[1].label=Empty Dataset

conquery.concepts[0].id=imdb
conquery.concepts[0].label=IMDb
conquery.concepts[0].dataset=imdb

conquery.entity-preview.all[0].name=imdb:entities
conquery.entity-preview.all[0].label=Entities
conquery.entity-preview.default[0].name=imdb:entities
conquery.entity-preview.default[0].label=Entities

conquery.frontend.query-upload.ids[0].name=ID
conquery.frontend.query-upload.ids[0].field=pid
conquery.frontend.query-upload.ids[0].label.und=result
conquery.frontend.query-upload.ids[0].primary-id=true
conquery.frontend.query-upload.ids[0].print=true
