// For displaying the "Tooltip"
export const DISPLAY_ADDITIONAL_INFOS = "tooltip/DISPLAY_ADDITIONAL_INFOS";
export const TOGGLE_ADDITIONAL_INFOS = "tooltip/TOGGLE_ADDITIONAL_INFOS";
export const TOGGLE_DISPLAY_TOOLTIP = "tooltip/TOGGLE_DISPLAY_TOOLTIP";
