package com.bakdata.conquery;


public class TestTags {

	public static final String INTEGRATION_PROGRAMMATIC = "INTEGRATION_PROGRAMMATIC";
	public static final String INTEGRATION_JSON = "INTEGRATION_JSON";
	public static final String INTEGRATION_SQL_BACKEND = "INTEGRATION_SQL_BACKEND";

	public static final String TEST_DIRECTORY_ENVIRONMENT_VARIABLE = "CONQUERY_TEST_DIRECTORY";
	public static final String SQL_BACKEND_TEST_DIRECTORY_ENVIRONMENT_VARIABLE = "SQL_TEST_DIRECTORY";

	public static final String TEST_PROGRAMMATIC_REGEX_FILTER = "CONQUERY_TEST_PROGRAMMATIC_REGEX_FILTER";

}
