trigger:
- master
- develop

variables:
- group: ConqueryConstants

pool:
  vmImage: $(IMAGE)
steps:
- checkout: self
  persistCredentials: true
- task: Maven@3
  displayName: build conquery
  inputs:
    jdkVersionOption: '1.11'
    goals: install
    options: $(MVN) -T 1C -DskipTests -pl !frontend-resources,!executable
- task: Maven@3
  displayName: autodoc
  inputs:
    jdkVersionOption: '1.11'
    goals: exec:java
    mavenPomFile: autodoc/pom.xml
    options: $(MVN) -Dexec.mainClass="com.bakdata.conquery.AutoDoc" -Dexec.arguments=docs
- task: Bash@3
  displayName: push new docs
  inputs:
    targetType: inline
    workingDirectory: docs/
    script: |
      git diff --quiet HEAD || \
      {
        echo "Documentation needs updated"
        git config --global user.email "bot@bakdata.com"
        git config --global user.name "bakdata-bot"
        git add *
        git commit --message "automatic update to docs"
        git push origin --set-upstream $(System.PullRequest.SourceBranch)
        echo "Documentation updated"
        exit -1
      }