pr:
  branches:
    include:
      - "*"
  paths:
    # Wild cards are not supported with path filters (In PR trigger). https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#paths
    include:
      - "pom.xml"
      - "backend"
      - "autodoc"
    exclude:
      - "frontend"

variables:
  - group: ConqueryConstants

pool:
  vmImage: $(IMAGE)
steps:
  - checkout: self
    persistCredentials: true
  - task: Maven@3
    displayName: build conquery
    inputs:
      jdkVersionOption: "1.11"
      goals: package
      options: $(MVN) -T 1C -DskipTests -pl !executable
  - task: Bash@3
    displayName: Pull and reset
    inputs:
      targetType: inline
      workingDirectory: ./
      script: |
        git fetch
        git checkout $(System.PullRequest.SourceBranch)
  - task: Maven@3
    displayName: autodoc
    inputs:
      jdkVersionOption: "1.11"
      goals: exec:java
      mavenPomFile: autodoc/pom.xml
      options: $(MVN) -Dexec.mainClass="com.bakdata.conquery.AutoDoc" -Dexec.arguments=docs
  - task: Bash@3
    displayName: push new docs
    inputs:
      targetType: inline
      workingDirectory: ./
      script: |
        echo "Diffing the generated docs with the previous state"

        if git diff --quiet HEAD
        then
          echo "No changes detected"
          exit 0
        fi

        echo "Documentation needs update"
        git config --global user.email "bot@bakdata.com"
        git config --global user.name "bakdata-bot"
        git add docs/*
        git commit --message "automatic update to docs"
        git push
        echo "Documentation updated"
        exit -1
