quarkus.http.root-path=/
quarkus.smallrye-openapi.path=/q/openapi
quarkus.package.jar.type=mutable-jar
quarkus.package.jar.user-providers-directory=providers
conquery.storage.backend=IN_MEMORY
%test.conquery.metadata.enabled=false

# The backend is consumed as a library by this downstream test application.
quarkus.index-dependency.backend.group-id=com.bakdata.conquery
quarkus.index-dependency.backend.artifact-id=backend-quarkus
