// PREVIOUS QUERIES
export const LOAD_PREVIOUS_QUERIES_START =
  "previous-queries/LOAD_PREVIOUS_QUERIES_START";
export const LOAD_PREVIOUS_QUERIES_SUCCESS =
  "previous-queries/LOAD_PREVIOUS_QUERIES_SUCCESS";
export const LOAD_PREVIOUS_QUERIES_ERROR =
  "previous-queries/LOAD_PREVIOUS_QUERIES_ERROR";

export const LOAD_PREVIOUS_QUERY_START =
  "previous-queries/LOAD_PREVIOUS_QUERY_START";
export const LOAD_PREVIOUS_QUERY_SUCCESS =
  "previous-queries/LOAD_PREVIOUS_QUERY_SUCCESS";
export const LOAD_PREVIOUS_QUERY_ERROR =
  "previous-queries/LOAD_PREVIOUS_QUERY_ERROR";

export const RENAME_PREVIOUS_QUERY_START =
  "previous-queries/RENAME_PREVIOUS_QUERY_START";
export const RENAME_PREVIOUS_QUERY_SUCCESS =
  "previous-queries/RENAME_PREVIOUS_QUERY_SUCCESS";
export const RENAME_PREVIOUS_QUERY_ERROR =
  "previous-queries/RENAME_PREVIOUS_QUERY_ERROR";

export const TOGGLE_EDIT_PREVIOUS_QUERY_LABEL =
  "previous-queries/TOGGLE_EDIT_PREVIOUS_QUERY_LABEL";
export const TOGGLE_EDIT_PREVIOUS_QUERY_TAGS =
  "previous-queries/TOGGLE_EDIT_PREVIOUS_QUERY_TAGS";

export const RETAG_PREVIOUS_QUERY_START =
  "previous-queries/RETAG_PREVIOUS_QUERY_START";
export const RETAG_PREVIOUS_QUERY_SUCCESS =
  "previous-queries/RETAG_PREVIOUS_QUERY_SUCCESS";
export const RETAG_PREVIOUS_QUERY_ERROR =
  "previous-queries/RETAG_PREVIOUS_QUERY_ERROR";

export const TOGGLE_SHARE_PREVIOUS_QUERY_START =
  "previous-queries/TOGGLE_SHARE_PREVIOUS_QUERY_START";
export const TOGGLE_SHARE_PREVIOUS_QUERY_SUCCESS =
  "previous-queries/TOGGLE_SHARE_PREVIOUS_QUERY_SUCCESS";
export const TOGGLE_SHARE_PREVIOUS_QUERY_ERROR =
  "previous-queries/TOGGLE_SHARE_PREVIOUS_QUERY_ERROR";

export const DELETE_PREVIOUS_QUERY_START =
  "previous-queries/DELETE_PREVIOUS_QUERY_START";
export const DELETE_PREVIOUS_QUERY_SUCCESS =
  "previous-queries/DELETE_PREVIOUS_QUERY_SUCCESS";
export const DELETE_PREVIOUS_QUERY_ERROR =
  "previous-queries/DELETE_PREVIOUS_QUERY_ERROR";
