export const DELETE_PREVIOUS_QUERY_MODAL_OPEN =
  "previous-queries/DELETE_PREVIOUS_QUERY_MODAL_OPEN";
export const DELETE_PREVIOUS_QUERY_MODAL_CLOSE =
  "previous-queries/DELETE_PREVIOUS_QUERY_MODAL_CLOSE";
