export const UPDATE_PREVIOUS_QUERIES_SEARCH =
  "previous-queries/UPDATE_PREVIOUS_QUERIES_SEARCH";
export const ADD_TAG_TO_PREVIOUS_QUERIES_SEARCH =
  "previous-queries/ADD_TAG_TO_PREVIOUS_QUERIES_SEARCH";
