// @flow
/* eslint-disable max-len */

// QUERY NODE MODAL
export const SET_STANDARD_NODE = "query-node-modal/SET_STANDARD_NODE";
export const CLEAR_STANDARD_NODE = "query-node-modal/CLEAR_STANDARD_NODE";
export const TOGGLE_STANDARD_TABLE = "query-node-modal/TOGGLE_STANDARD_TABLE";
export const SET_STANDARD_FILTER_VALUE = "query-node-modal/SET_STANDARD_FILTER_VALUE";
export const RESET_STANDARD_ALL_FILTERS = "query-node-modal/RESET_STANDARD_ALL_FILTERS";
export const SWITCH_STANDARD_FILTER_MODE = "query-node-modal/SWITCH_STANDARD_FILTER_MODE";
export const TOGGLE_STANDARD_TIMESTAMPS = "query-node-modal/TOGGLE_STANDARD_TIMESTAMPS";
export const LOAD_STANDARD_FILTER_SUGGESTIONS_START = "query-node-modal/LOAD_STANDARD_FILTER_SUGGESTIONS_START";
export const LOAD_STANDARD_FILTER_SUGGESTIONS_SUCCESS = "query-node-modal/LOAD_STANDARD_FILTER_SUGGESTIONS_SUCCESS";
export const LOAD_STANDARD_FILTER_SUGGESTIONS_ERROR = "query-node-modal/LOAD_STANDARD_FILTER_SUGGESTIONS_ERROR";
