package com.bakdata.conquery.sql.compiler.ir.form;

import java.sql.Date;

import com.bakdata.conquery.sql.compiler.ir.SharedAliases;
import lombok.experimental.UtilityClass;
import org.jooq.Field;
import org.jooq.impl.DSL;

/**
 * SQL fields shared by absolute, entity-date, and relative form compilation.
 */
@UtilityClass
public class FormConstants {

	/**
	 * The index date from which an absolute stratification for an entity starts. It is the lowest date bound of an absolute stratification.
	 */
	public static final Field<Date> INDEX_START = DSL.field(DSL.name(SharedAliases.INDEX_START.getAlias()), Date.class);

	/**
	 * The index date selected by a relative stratification's temporal sampler.
	 */
	public static final Field<Date> INDEX_SELECTOR = DSL.field(DSL.name(SharedAliases.INDEX_SELECTOR.getAlias()), Date.class);

	/**
	 * The index date from which we start when calculating a feature range.
	 */
	public static final Field<Date> INDEX_START_NEGATIVE = DSL.field(DSL.name(SharedAliases.INDEX_START_NEGATIVE.getAlias()), Date.class);

	/**
	 * The index date from which we start when calculating an outcome range.
	 */
	public static final Field<Date> INDEX_START_POSITIVE = DSL.field(DSL.name(SharedAliases.INDEX_START_POSITIVE.getAlias()), Date.class);

	/**
	 * The quarter start of the lower bound of an absolute stratification range.
	 */
	public static final Field<Date> QUARTER_START = DSL.field(DSL.name(SharedAliases.QUARTER_START.getAlias()), Date.class);

	/**
	 * The exclusive quarter end of the upper bound of an absolute stratification range.
	 */
	public static final Field<Date> QUARTER_END = DSL.field(DSL.name(SharedAliases.QUARTER_END.getAlias()), Date.class);

	/**
	 * The year start of the lower bound of an absolute stratification range.
	 */
	public static final Field<Date> YEAR_START = DSL.field(DSL.name(SharedAliases.YEAR_START.getAlias()), Date.class);

	/**
	 * The year end of the upper bound of an absolute stratification range.
	 */
	public static final Field<Date> YEAR_END = DSL.field(DSL.name(SharedAliases.YEAR_END.getAlias()), Date.class);

	/**
	 * The year end of the upper bound of an absolute stratification range, aligned on the lower bound's quarter start.
	 */
	public static final Field<Date> YEAR_END_QUARTER_ALIGNED = DSL.field(DSL.name(SharedAliases.YEAR_END_QUARTER_ALIGNED.getAlias()), Date.class);

	/**
	 * The amount times an interval added to a date, aligned on a year.
	 */
	public static final Field<Integer> YEAR_ALIGNED_COUNT = DSL.field(DSL.name(SharedAliases.YEAR_ALIGNED_COUNT.getAlias()), Integer.class);

	/**
	 * The amount times an interval added to a date, aligned on a quarter.
	 */
	public static final Field<Integer> QUARTER_ALIGNED_COUNT = DSL.field(DSL.name(SharedAliases.QUARTER_ALIGNED_COUNT.getAlias()), Integer.class);

	/**
	 * The amount times an interval added to a date, aligned a day.
	 */
	public static final Field<Integer> DAY_ALIGNED_COUNT = DSL.field(DSL.name(SharedAliases.DAY_ALIGNED_COUNT.getAlias()), Integer.class);

	/**
	 * The int field generated by a generate_series SQL set-returning function.
	 */
	public static final Field<Integer> SERIES_INDEX = DSL.field(DSL.name(SharedAliases.SERIES_INDEX.getAlias()), Integer.class);

}
