// flow-typed signature: 40f173298d8d9c541c1ff050181fb870
// flow-typed version: <<STUB>>/eslint-config-standard-react_v^4.3.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-standard-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-standard-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-standard-react/test/basic' {
  declare module.exports: any;
}

declare module 'eslint-config-standard-react/test/validate-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-standard-react/index' {
  declare module.exports: $Exports<'eslint-config-standard-react'>;
}
declare module 'eslint-config-standard-react/index.js' {
  declare module.exports: $Exports<'eslint-config-standard-react'>;
}
declare module 'eslint-config-standard-react/test/basic.js' {
  declare module.exports: $Exports<'eslint-config-standard-react/test/basic'>;
}
declare module 'eslint-config-standard-react/test/validate-config.js' {
  declare module.exports: $Exports<'eslint-config-standard-react/test/validate-config'>;
}
