// flow-typed signature: f91342076063faae68cd32cfa45dcd24
// flow-typed version: <<STUB>>/flux-standard-action_v^0.6.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flux-standard-action'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flux-standard-action' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flux-standard-action/lib/__tests__/init' {
  declare module.exports: any;
}

declare module 'flux-standard-action/lib/__tests__/isError-test' {
  declare module.exports: any;
}

declare module 'flux-standard-action/lib/__tests__/isFSA-test' {
  declare module.exports: any;
}

declare module 'flux-standard-action/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flux-standard-action/lib/__tests__/init.js' {
  declare module.exports: $Exports<'flux-standard-action/lib/__tests__/init'>;
}
declare module 'flux-standard-action/lib/__tests__/isError-test.js' {
  declare module.exports: $Exports<'flux-standard-action/lib/__tests__/isError-test'>;
}
declare module 'flux-standard-action/lib/__tests__/isFSA-test.js' {
  declare module.exports: $Exports<'flux-standard-action/lib/__tests__/isFSA-test'>;
}
declare module 'flux-standard-action/lib/index.js' {
  declare module.exports: $Exports<'flux-standard-action/lib/index'>;
}
