// flow-typed signature: 178a9f01332cf544d10f65f2b174f88c
// flow-typed version: <<STUB>>/i18n-react_v^0.6.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18n-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18n-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18n-react/dist/i18n-react' {
  declare module.exports: any;
}

declare module 'i18n-react/dist/i18n-react.umd' {
  declare module.exports: any;
}

declare module 'i18n-react/dist/i18n-react.umd.min' {
  declare module.exports: any;
}

declare module 'i18n-react/dist/mdflavors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18n-react/dist/i18n-react.js' {
  declare module.exports: $Exports<'i18n-react/dist/i18n-react'>;
}
declare module 'i18n-react/dist/i18n-react.umd.js' {
  declare module.exports: $Exports<'i18n-react/dist/i18n-react.umd'>;
}
declare module 'i18n-react/dist/i18n-react.umd.min.js' {
  declare module.exports: $Exports<'i18n-react/dist/i18n-react.umd.min'>;
}
declare module 'i18n-react/dist/mdflavors.js' {
  declare module.exports: $Exports<'i18n-react/dist/mdflavors'>;
}
