// flow-typed signature: 5f74bc0aeb73d257e7ee2f3772ed2308
// flow-typed version: <<STUB>>/react-split-pane_v^0.1.57/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-split-pane'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-split-pane' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-split-pane/demo/bundle' {
  declare module.exports: any;
}

declare module 'react-split-pane/demo/Examples' {
  declare module.exports: any;
}

declare module 'react-split-pane/lib/Pane' {
  declare module.exports: any;
}

declare module 'react-split-pane/lib/Resizer' {
  declare module.exports: any;
}

declare module 'react-split-pane/lib/SplitPane' {
  declare module.exports: any;
}

declare module 'react-split-pane/test/assertions/Asserter' {
  declare module.exports: any;
}

declare module 'react-split-pane/test/default-split-pane-tests' {
  declare module.exports: any;
}

declare module 'react-split-pane/test/horizontal-split-pane-tests' {
  declare module.exports: any;
}

declare module 'react-split-pane/test/vertical-split-pane-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-split-pane/demo/bundle.js' {
  declare module.exports: $Exports<'react-split-pane/demo/bundle'>;
}
declare module 'react-split-pane/demo/Examples.js' {
  declare module.exports: $Exports<'react-split-pane/demo/Examples'>;
}
declare module 'react-split-pane/index' {
  declare module.exports: $Exports<'react-split-pane'>;
}
declare module 'react-split-pane/index.js' {
  declare module.exports: $Exports<'react-split-pane'>;
}
declare module 'react-split-pane/lib/Pane.js' {
  declare module.exports: $Exports<'react-split-pane/lib/Pane'>;
}
declare module 'react-split-pane/lib/Resizer.js' {
  declare module.exports: $Exports<'react-split-pane/lib/Resizer'>;
}
declare module 'react-split-pane/lib/SplitPane.js' {
  declare module.exports: $Exports<'react-split-pane/lib/SplitPane'>;
}
declare module 'react-split-pane/test/assertions/Asserter.js' {
  declare module.exports: $Exports<'react-split-pane/test/assertions/Asserter'>;
}
declare module 'react-split-pane/test/default-split-pane-tests.js' {
  declare module.exports: $Exports<'react-split-pane/test/default-split-pane-tests'>;
}
declare module 'react-split-pane/test/horizontal-split-pane-tests.js' {
  declare module.exports: $Exports<'react-split-pane/test/horizontal-split-pane-tests'>;
}
declare module 'react-split-pane/test/vertical-split-pane-tests.js' {
  declare module.exports: $Exports<'react-split-pane/test/vertical-split-pane-tests'>;
}
