// flow-typed signature: 1bb7b7f53e88ea757be9eeadf1e9d26d
// flow-typed version: <<STUB>>/react-onclickoutside_v^5.7.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onclickoutside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onclickoutside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-onclickoutside/test/browser/testit' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/test/karma.conf' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/test/no-dom-test' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-onclickoutside/index' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
declare module 'react-onclickoutside/index.js' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
declare module 'react-onclickoutside/test/browser/testit.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/browser/testit'>;
}
declare module 'react-onclickoutside/test/karma.conf.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/karma.conf'>;
}
declare module 'react-onclickoutside/test/no-dom-test.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/no-dom-test'>;
}
declare module 'react-onclickoutside/test/test.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/test'>;
}
