// flow-typed signature: fa8f008b97c3b8219fb8ecb29b03d560
// flow-typed version: <<STUB>>/react-input-autosize_v^1.1.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-autosize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-input-autosize/dist/react-input-autosize' {
  declare module.exports: any;
}

declare module 'react-input-autosize/dist/react-input-autosize.min' {
  declare module.exports: any;
}

declare module 'react-input-autosize/example/src/app' {
  declare module.exports: any;
}

declare module 'react-input-autosize/lib/AutosizeInput' {
  declare module.exports: any;
}

declare module 'react-input-autosize/src/AutosizeInput' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-input-autosize/dist/react-input-autosize.js' {
  declare module.exports: $Exports<'react-input-autosize/dist/react-input-autosize'>;
}
declare module 'react-input-autosize/dist/react-input-autosize.min.js' {
  declare module.exports: $Exports<'react-input-autosize/dist/react-input-autosize.min'>;
}
declare module 'react-input-autosize/example/src/app.js' {
  declare module.exports: $Exports<'react-input-autosize/example/src/app'>;
}
declare module 'react-input-autosize/lib/AutosizeInput.js' {
  declare module.exports: $Exports<'react-input-autosize/lib/AutosizeInput'>;
}
declare module 'react-input-autosize/src/AutosizeInput.js' {
  declare module.exports: $Exports<'react-input-autosize/src/AutosizeInput'>;
}
