// flow-typed signature: 187ca8f0d6807f0aa03b076e2ddb62cd
// flow-typed version: <<STUB>>/timekeeper_v^2.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timekeeper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timekeeper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timekeeper/lib/timekeeper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timekeeper/lib/timekeeper.js' {
  declare module.exports: $Exports<'timekeeper/lib/timekeeper'>;
}
