// @flow

// QUERY RUNNER
export const START_TIMEBASED_QUERY_START = "query-runners/START_TIMEBASED_QUERY_START";
export const START_TIMEBASED_QUERY_SUCCESS = "query-runners/START_TIMEBASED_QUERY_SUCCESS";
export const START_TIMEBASED_QUERY_ERROR = "query-runners/START_TIMEBASED_QUERY_ERROR";
export const STOP_TIMEBASED_QUERY_START = "query-runners/STOP_TIMEBASED_QUERY_START";
export const STOP_TIMEBASED_QUERY_SUCCESS = "query-runners/STOP_TIMEBASED_QUERY_SUCCESS";
export const STOP_TIMEBASED_QUERY_ERROR = "query-runners/STOP_TIMEBASED_QUERY_ERROR";
export const QUERY_TIMEBASED_RESULT_START = "query-runners/QUERY_TIMEBASED_RESULT_START";
export const QUERY_TIMEBASED_RESULT_STOP = "query-runners/QUERY_TIMEBASED_RESULT_STOP";
export const QUERY_TIMEBASED_RESULT_SUCCESS = "query-runners/QUERY_TIMEBASED_RESULT_SUCCESS";
export const QUERY_TIMEBASED_RESULT_ERROR = "query-runners/QUERY_TIMEBASED_RESULT_ERROR";

export const START_STANDARD_QUERY_START = "query-runners/START_STANDARD_QUERY_START";
export const START_STANDARD_QUERY_SUCCESS = "query-runners/START_STANDARD_QUERY_SUCCESS";
export const START_STANDARD_QUERY_ERROR = "query-runners/START_STANDARD_QUERY_ERROR";
export const STOP_STANDARD_QUERY_START = "query-runners/STOP_STANDARD_QUERY_START";
export const STOP_STANDARD_QUERY_SUCCESS = "query-runners/STOP_STANDARD_QUERY_SUCCESS";
export const STOP_STANDARD_QUERY_ERROR = "query-runners/STOP_STANDARD_QUERY_ERROR";
export const QUERY_STANDARD_RESULT_START = "query-runners/QUERY_STANDARD_RESULT_START";
export const QUERY_STANDARD_RESULT_STOP = "query-runners/QUERY_STANDARD_RESULT_STOP";
export const QUERY_STANDARD_RESULT_SUCCESS = "query-runners/QUERY_STANDARD_RESULT_SUCCESS";
export const QUERY_STANDARD_RESULT_ERROR = "query-runners/QUERY_STANDARD_RESULT_ERROR";

export const START_EXTERNAL_FORMS_QUERY_START = "query-runners/START_EXTERNAL_FORMS_QUERY_START";
export const START_EXTERNAL_FORMS_QUERY_SUCCESS =
    "query-runners/START_EXTERNAL_FORMS_QUERY_SUCCESS";
export const START_EXTERNAL_FORMS_QUERY_ERROR = "query-runners/START_EXTERNAL_FORMS_QUERY_ERROR";
export const STOP_EXTERNAL_FORMS_QUERY_START = "query-runners/STOP_EXTERNAL_FORMS_QUERY_START";
export const STOP_EXTERNAL_FORMS_QUERY_SUCCESS = "query-runners/STOP_EXTERNAL_FORMS_QUERY_SUCCESS";
export const STOP_EXTERNAL_FORMS_QUERY_ERROR = "query-runners/STOP_EXTERNAL_FORMS_QUERY_ERROR";
export const QUERY_EXTERNAL_FORMS_RESULT_START = "query-runners/QUERY_EXTERNAL_FORMS_RESULT_START";
export const QUERY_EXTERNAL_FORMS_RESULT_STOP = "query-runners/QUERY_EXTERNAL_FORMS_RESULT_STOP";
export const QUERY_EXTERNAL_FORMS_RESULT_SUCCESS =
    "query-runners/QUERY_EXTERNAL_FORMS_RESULT_SUCCESS";
export const QUERY_EXTERNAL_FORMS_RESULT_ERROR = "query-runners/QUERY_EXTERNAL_FORMS_RESULT_ERROR";
