package com.bakdata.conquery.sql.compiler.forms;

import static com.bakdata.conquery.sql.compiler.dialect.Interval.DAYS_PER_QUARTER;
import static com.bakdata.conquery.sql.compiler.dialect.Interval.DAYS_PER_YEAR;
import static com.bakdata.conquery.sql.compiler.dialect.Interval.MONTHS_PER_QUARTER;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.DAY_ALIGNED_COUNT;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.INDEX_SELECTOR;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.INDEX_START;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.QUARTER_ALIGNED_COUNT;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.QUARTER_END;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.QUARTER_START;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.YEAR_ALIGNED_COUNT;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.YEAR_END;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.YEAR_END_QUARTER_ALIGNED;
import static com.bakdata.conquery.sql.compiler.ir.form.FormConstants.YEAR_START;

import java.sql.Date;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import com.bakdata.conquery.sql.compiler.dialect.CompilerDialect;
import com.bakdata.conquery.sql.compiler.ir.SharedAliases;
import com.bakdata.conquery.sql.compiler.ir.form.Offset;
import com.bakdata.conquery.sql.compiler.dialect.Interval;
import com.bakdata.conquery.sql.compiler.ir.select.ColumnDateRange;
import com.bakdata.conquery.sql.compiler.ir.SqlIdColumns;
import com.bakdata.conquery.sql.model.form.FormCalendarUnit;
import com.bakdata.conquery.sql.model.form.FormIndexPlacement;
import com.bakdata.conquery.sql.model.form.FormIndexSelector;
import com.bakdata.conquery.sql.model.form.ResolutionAndAlignment;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.impl.DSL;

public abstract class StratificationFunctions {

	public ColumnDateRange ofStartAndEnd(Field<Date> start, Field<Date> end) {
		return ColumnDateRange.of(start, end); // needs to be overwritten for dialects that support single-column ranges
	}

	protected abstract CompilerDialect getDialect();

	/**
	 * Extract the lower bounds from a given daterange.
	 */
	public abstract Field<Date> lower(ColumnDateRange dateRange);

	/**
	 * Extract the inclusive upper bound from a given daterange.
	 */
	protected abstract Field<Date> inclusiveUpper(ColumnDateRange dateRange);

	/**
	 * Extract the exclusive upper bound from a given daterange.
	 */
	protected abstract Field<Date> exclusiveUpper(ColumnDateRange dateRange);

	/**
	 * Calculates the start and end date based on the given start date and an interval expression.
	 */
	protected abstract ColumnDateRange calcRange(Field<Date> start, Interval interval);

	/**
	 * Extracts the absolute index start date by using the lower bound of the provided date range.
	 */
	public abstract Field<Date> absoluteIndexStartDate(ColumnDateRange dateRange);

	/**
	 * Determines the start of the year based on the lower bound of the provided date range.
	 */
	public abstract Field<Date> lowerBoundYearStart(ColumnDateRange dateRange);

	/**
	 * Determines the exclusive end (first day of the next year) of the upper bound of the provided date range.
	 */
	public abstract Field<Date> upperBoundYearEnd(ColumnDateRange dateRange);

	/**
	 * Determines the end of the upper bound of the provided date range, but aligned on the quarter of the lower bound of the
	 * provided daterange.
	 */
	public abstract Field<Date> upperBoundYearEndQuarterAligned(ColumnDateRange dateRange);

	/**
	 * Calculates the start of the quarter using the lower bound of the provided date range.
	 */
	public abstract Field<Date> lowerBoundQuarterStart(ColumnDateRange dateRange);

	/**
	 * Calculates the start of the quarter of the given date.
	 */
	public abstract Field<Date> jumpToQuarterStart(Field<Date> date);

	/**
	 * Calculates the exclusive end (first day of the next quarter) of the upper bound of the provided date range.
	 */
	public abstract Field<Date> upperBoundQuarterEnd(ColumnDateRange dateRange);

	/**
	 * Calculates the start of the next quarter of the given date.
	 */
	public abstract Field<Date> jumpToNextQuarterStart(Field<Date> date);

	/**
	 * The int field generated by the {@link #generateIntSeries(int, int)}
	 */
	public abstract Field<Integer> intSeriesField();

	/**
	 * Generates a series of integers from the start value to the exclusive end value.
	 */
	public abstract Table<Record> generateIntSeries(int start, int end);

	/**
	 * Generates a date field representing the selected index strategy using the given validity date range.
	 */
	public abstract Field<Date> indexSelectorField(FormIndexSelector indexSelector, ColumnDateRange validityDate);

	/**
	 * Shift's a start date by an interval times an amount. The offset will we added to the amount before multiplying.
	 */
	public abstract Field<Date> shiftByInterval(Field<Date> startDate, Interval interval, Field<Integer> amount, Offset offset);

	/**
	 * Generates the start and end field for the respective index placement and time unit.
	 */
	public List<Field<Date>> indexStartFields(FormIndexPlacement indexPlacement, FormCalendarUnit timeUnit) {

		Field<Date> positiveStart;
		Field<Date> negativeStart;

		switch (timeUnit) {
			case QUARTERS -> {
				switch (indexPlacement) {
					case BEFORE -> {
						Field<Date> nextQuarterStart = jumpToNextQuarterStart(INDEX_SELECTOR);
						positiveStart = nextQuarterStart;
						negativeStart = nextQuarterStart;
					}
					case AFTER -> {
						Field<Date> quarterStart = jumpToQuarterStart(INDEX_SELECTOR);
						positiveStart = quarterStart;
						negativeStart = quarterStart;
					}
					case NEUTRAL -> {
						positiveStart = jumpToNextQuarterStart(INDEX_SELECTOR);
						negativeStart = jumpToQuarterStart(INDEX_SELECTOR);
					}
					default -> throw new CombinationNotSupportedException(indexPlacement, timeUnit);
				}
			}
			case DAYS -> {
				switch (indexPlacement) {
					case BEFORE, AFTER -> {
						positiveStart = INDEX_SELECTOR;
						negativeStart = INDEX_SELECTOR;
					}
					case NEUTRAL -> {
						positiveStart = getDialect().addDays(INDEX_SELECTOR, DSL.inline(1));
						negativeStart = INDEX_SELECTOR;
					}
					default -> throw new CombinationNotSupportedException(indexPlacement, timeUnit);
				}
			}
			default -> throw new CombinationNotSupportedException(indexPlacement, timeUnit);
		}

		return List.of(
				positiveStart.as(SharedAliases.INDEX_START_POSITIVE.getAlias()),
				negativeStart.as(SharedAliases.INDEX_START_NEGATIVE.getAlias())
		);
	}

	/**
	 * Calculates the count of the required resolution windows based on the provided resolution, alignment, and date range.
	 *
	 * @return A {@link Field<Integer>} representing the count of resolution windows.
	 * @throws CombinationNotSupportedException if the combination of resolution and alignment is not supported.
	 */
	public Field<Integer> calculateResolutionWindowCount(ResolutionAndAlignment resolutionAndAlignment, ColumnDateRange bounds) {
		CompilerDialect functionProvider = getDialect();
		return switch (resolutionAndAlignment.getResolution()) {
			case COMPLETE -> DSL.inline(1);
			case YEARS -> calculateResolutionWindowForYearResolution(resolutionAndAlignment, bounds, functionProvider);
			case QUARTERS -> calculateResolutionWindowForQuarterResolution(resolutionAndAlignment, bounds, functionProvider);
			case DAYS -> functionProvider.dateDistance(ChronoUnit.DAYS, lower(bounds), exclusiveUpper(bounds))
										 .as(SharedAliases.DAY_ALIGNED_COUNT.getAlias());
		};
	}

	/**
	 * Determines the stratification range based on resolution and alignment parameters. The created stratification range is bound by the given range.
	 */
	public ColumnDateRange createStratificationRange(ResolutionAndAlignment resolutionAndAlignment, ColumnDateRange bounds) {

		CompilerDialect functionProvider = getDialect();

		ColumnDateRange stratificationRange = switch (resolutionAndAlignment.getResolution()) {
			case COMPLETE -> bounds;
			case YEARS -> createStratificationRangeForYearResolution(resolutionAndAlignment);
			case QUARTERS -> createStratificationRangeForQuarterResolution(resolutionAndAlignment);
			case DAYS -> calcRange(INDEX_START, Interval.ONE_DAY_INTERVAL);
		};

		return functionProvider.intersection(stratificationRange, bounds).as(bounds.getAlias());
	}

	/**
	 * The index field for the corresponding resolution index.
	 */
	public Field<Integer> index(SqlIdColumns ids, Optional<ColumnDateRange> stratificationBounds) {

		List<Field<?>> partitioningFields =
				Stream.concat(
							  ids.toFields().stream(),
							  stratificationBounds.stream().flatMap(columnDateRange -> columnDateRange.toFields().stream())
					  )
					  .collect(Collectors.toList());

		return DSL.rowNumber()
				  .over(DSL.partitionBy(partitioningFields))
				  .as(SharedAliases.INDEX.getAlias());
	}

	/**
	 * Generates a condition to limit the resolution window count in a query.
	 * This method applies a check to ensure the series index does not exceed the maximum window count based on the given resolution and alignment.
	 */
	public Condition stopOnMaxResolutionWindowCount(ResolutionAndAlignment resolutionAndAlignment) {
		Field<Integer> seriesIndex = intSeriesField();
		return switch (resolutionAndAlignment.getResolution()) {
			case COMPLETE -> DSL.noCondition();
			case YEARS -> windowCountForYearResolution(resolutionAndAlignment, seriesIndex);
			case QUARTERS -> windowCountForQuarterResolution(resolutionAndAlignment, seriesIndex);
			case DAYS -> seriesIndex.lessOrEqual(DAY_ALIGNED_COUNT);
		};
	}

	private Field<Integer> calculateResolutionWindowForQuarterResolution(
			ResolutionAndAlignment resolutionAndAlignment,
			ColumnDateRange bounds,
			CompilerDialect functionProvider
	) {
		return switch (resolutionAndAlignment.getAlignment()) {
			case QUARTER -> functionProvider.dateDistance(ChronoUnit.MONTHS, QUARTER_START, QUARTER_END)
											.divide(MONTHS_PER_QUARTER)
											.as(SharedAliases.QUARTER_ALIGNED_COUNT.getAlias());
			case DAY -> functionProvider.dateDistance(ChronoUnit.DAYS, lower(bounds), exclusiveUpper(bounds))
										.plus(89)
										.divide(DAYS_PER_QUARTER)
										.as(SharedAliases.DAY_ALIGNED_COUNT.getAlias());
			default -> throw new CombinationNotSupportedException(resolutionAndAlignment);
		};
	}

	private Field<Integer> calculateResolutionWindowForYearResolution(
			ResolutionAndAlignment resolutionAndAlignment,
			ColumnDateRange bounds,
			CompilerDialect functionProvider
	) {
		return switch (resolutionAndAlignment.getAlignment()) {
			case YEAR -> functionProvider.dateDistance(ChronoUnit.YEARS, YEAR_START, YEAR_END)
										 .as(SharedAliases.YEAR_ALIGNED_COUNT.getAlias());
			case QUARTER -> functionProvider.dateDistance(ChronoUnit.YEARS, QUARTER_START, YEAR_END_QUARTER_ALIGNED)
											.as(SharedAliases.QUARTER_ALIGNED_COUNT.getAlias());
			case DAY -> functionProvider.dateDistance(ChronoUnit.DAYS, lower(bounds), exclusiveUpper(bounds))
										.plus(364)
										.divide(DAYS_PER_YEAR)
										.as(SharedAliases.DAY_ALIGNED_COUNT.getAlias());
			default -> throw new CombinationNotSupportedException(resolutionAndAlignment);
		};
	}

	private ColumnDateRange createStratificationRangeForQuarterResolution(ResolutionAndAlignment resolutionAndAlignment) {
		return switch (resolutionAndAlignment.getAlignment()) {
			case QUARTER -> calcRange(QUARTER_START, Interval.QUARTER_INTERVAL);
			case DAY -> calcRange(INDEX_START, Interval.NINETY_DAYS_INTERVAL);
			default -> throw new CombinationNotSupportedException(resolutionAndAlignment);
		};
	}

	private ColumnDateRange createStratificationRangeForYearResolution(ResolutionAndAlignment resolutionAndAlignment) {
		return switch (resolutionAndAlignment.getAlignment()) {
			case YEAR -> calcRange(YEAR_START, Interval.ONE_YEAR_INTERVAL);
			case QUARTER -> calcRange(QUARTER_START, Interval.ONE_YEAR_INTERVAL);
			case DAY -> calcRange(INDEX_START, Interval.YEAR_AS_DAYS_INTERVAL);
			default -> throw new CombinationNotSupportedException(resolutionAndAlignment);
		};
	}

	private static Condition windowCountForQuarterResolution(ResolutionAndAlignment resolutionAndAlignment, Field<Integer> seriesIndex) {
		return switch (resolutionAndAlignment.getAlignment()) {
			case QUARTER -> seriesIndex.lessOrEqual(QUARTER_ALIGNED_COUNT);
			case DAY -> seriesIndex.lessOrEqual(DAY_ALIGNED_COUNT);
			default -> throw new CombinationNotSupportedException(resolutionAndAlignment);
		};
	}

	private static Condition windowCountForYearResolution(ResolutionAndAlignment resolutionAndAlignment, Field<Integer> seriesIndex) {
		return switch (resolutionAndAlignment.getAlignment()) {
			case YEAR -> seriesIndex.lessOrEqual(YEAR_ALIGNED_COUNT);
			case QUARTER -> seriesIndex.lessOrEqual(QUARTER_ALIGNED_COUNT);
			case DAY -> seriesIndex.lessOrEqual(DAY_ALIGNED_COUNT);
			default -> throw new CombinationNotSupportedException(resolutionAndAlignment);
		};
	}

}
