export const EARLIEST = "EARLIEST";
export const LATEST = "LATEST";
export const RANDOM = "RANDOM";

export const TIMEBASED_TIMESTAMP_TYPES = {
  EARLIEST: EARLIEST,
  LATEST: LATEST,
  RANDOM: RANDOM
};
