export const BEFORE = "BEFORE";
export const BEFORE_OR_SAME = "BEFORE_OR_SAME";
export const SAME = "SAME";
export const DAYS_BEFORE = "DAYS_BEFORE";
export const DAYS_OR_NO_EVENT_BEFORE = "DAYS_OR_NO_EVENT_BEFORE";

export const TIMEBASED_OPERATOR_TYPES = {
  BEFORE: BEFORE,
  BEFORE_OR_SAME: BEFORE_OR_SAME,
  SAME: SAME,
  DAYS_BEFORE: DAYS_BEFORE,
  DAYS_OR_NO_EVENT_BEFORE: DAYS_OR_NO_EVENT_BEFORE,
};
