name: "OpenAPI linter"
on:
  pull_request:
    paths:
      - "openapi.yaml"
      - "backend/src/main/resources/com/bakdata/conquery/external/openapi-form-backend.yaml"
      - ".github/workflows/lint_openapi.yaml"
jobs:
  lint:
    runs-on: ubuntu-latest
    container: dshanley/vacuum
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: "Lint OpenApi spec for /api"
        run: vacuum lint --details ./openapi.yaml
      - name: "Lint OpenApi spec for external form backends"
        run: vacuum lint --details ./backend/src/main/resources/com/bakdata/conquery/external/openapi-form-backend.yaml
