name: Helm Lint and Template Validation

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint Helm Chart
        run: helm lint charts/conquery

      - name: Validate Helm Templates
        run: helm template conquery charts/conquery --debug
