name: "End-To-End Tests"

on:
  push:
    branches:
      # Always run on protected branches
      - master
      - develop
      - release
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Set electron language to german so request use "accept-language: de" header
      ELECTRON_EXTRA_LAUNCH_ARGS: --lang=de
    timeout-minutes: 10
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            frontend/pnpm-lock.yaml

      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
          overwrite-settings: false

      - name: Build Backend
        run: ./scripts/build_backend_no_version.sh

      - name: Build Frontend
        run: ./scripts/build_frontend.sh

      - name: Cypress run
        # This is a preconfigured action, maintained by cypress, to run e2e tests
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@09090944bd8aaa2a517cefb6e38bf1aae336b42b # v7.4.3
        with:
          working-directory: .
          start: bash ./scripts/run_e2e_all.sh
          wait-on: "http://localhost:8000"

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
