name: "End-To-End Tests"

on: [push]
jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Backend
        run: ./scripts/build_version.sh

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          build: 
          install-command: yarn --ignore-platform --frozen-lockfile
          start: echo PWD $(pwd); ../scripts/run_conquery_cypress.sh
          wait-on: 'npx wait-on --timeout 5000 http://localhost:3000; ../scripts/load_test_data_cypress.sh'