# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test building backend image

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - develop
      - master
    paths:
      - 'backend/**'
      - 'executable/**'
      - 'Dockerfile'
      - 'pom.xml'
      - 'lombok.config'
      - 'scripts/**'
      - '.github/workflows/test_build_backend_image.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  test-build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all tags
          fetch-depth: 0

      - name: Build docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
